### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by ucciote** [M3nny/open-sagra#1]
Salve! Mi interesserebbe provare questa webapp, sarebbe possibile avere il file sql per la generazione del DB?

**Comment by M3nny** [comment]
Salve, ho appena aggiunto il file per generare il DB ed ho aggiornato il README con delle informazioni utili.
Una curiosità: posso chiederle come ha scoperto questa repository?

**Comment by ucciote** [comment]
Grazie! Navigando e cercando soluzioni per la gestione di una sagra, partendo dai repo più recenti...
